name: Lint schemas

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Set up pnpm
        uses: pnpm/action-setup@v3

      - run: pnpm lint
